### PR TITLE
Sync Block Coding plugin to v0.7.0

### PR DESCRIPTION
**Pull request by starnight**
Latest Block Coding plugin has a big change. So, sync it to v0.7.0. This will break the original dependency. So, the demos have to be updated accordingly.

https://phabricator.endlessm.com/T35683

### CODE REVIEW

**Comment by manuq** [comment]
@starnight thanks! I think we can wait a little bit for @cassidyjames to merge the Pachinko game first and for more architectural changes to be completed.

**Comment by starnight** [comment]
yap! sure!

**Comment by manuq** [comment]
@starnight would you like to sync the platformer with the current block version in the `godotcon` branch? Basically redo this PR targetting the `godotcon` branch.

**Comment by starnight** [comment]
Yap!  Rebasing now.  Will re-target to godotcon branch.

**Pull request closed without merging**
